"""Replaced Penerima fields with location data

Revision ID: 5f5e338d3823
Revises: c40af6e965eb
Create Date: 2025-07-15 11:44:42.005404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f5e338d3823'
down_revision = 'c40af6e965eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kriteria_penerima')
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provinsi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kabupaten', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kecamatan', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('desa', sa.String(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_penerima_nik'))
        batch_op.drop_index(batch_op.f('ix_penerima_no_kk'))
        batch_op.create_index(batch_op.f('ix_penerima_nama'), ['nama'], unique=False)
        batch_op.drop_column('nik')
        batch_op.drop_column('alamat_lengkap')
        batch_op.drop_column('dtks')
        batch_op.drop_column('no_kk')
        batch_op.drop_column('dokumen_pendukung_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dokumen_pendukung_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('no_kk', mysql.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('dtks', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('alamat_lengkap', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('nik', mysql.VARCHAR(length=16), nullable=False))
        batch_op.drop_index(batch_op.f('ix_penerima_nama'))
        batch_op.create_index(batch_op.f('ix_penerima_no_kk'), ['no_kk'], unique=False)
        batch_op.create_index(batch_op.f('ix_penerima_nik'), ['nik'], unique=True)
        batch_op.drop_column('desa')
        batch_op.drop_column('kecamatan')
        batch_op.drop_column('kabupaten')
        batch_op.drop_column('provinsi')

    op.create_table('kriteria_penerima',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('penerima_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nama_kriteria', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nilai_kriteria', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima.id'], name=op.f('kriteria_penerima_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
