"""Replace alamat_lengkap with location dropdowns

Revision ID: a1d2a14f178e
Revises: 5f5e338d3823
Create Date: 2025-07-15 11:57:19.722358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d2a14f178e'
down_revision = '5f5e338d3823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kriteria_penerima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penerima_id', sa.Integer(), nullable=False),
    sa.Column('nama_kriteria', sa.String(length=100), nullable=False),
    sa.Column('nilai_kriteria', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dtks', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dokumen_pendukung_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.drop_column('dokumen_pendukung_path')
        batch_op.drop_column('dtks')

    op.drop_table('kriteria_penerima')
    # ### end Alembic commands ###
