"""Initial migration for MySQL

Revision ID: c40af6e965eb
Revises: 
Create Date: 2025-06-13 01:33:57.393054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40af6e965eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penerima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('no_kk', sa.String(length=16), nullable=False),
    sa.Column('alamat_lengkap', sa.Text(), nullable=True),
    sa.Column('dtks', sa.String(length=10), nullable=True),
    sa.Column('dokumen_pendukung_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penerima_nik'), ['nik'], unique=True)
        batch_op.create_index(batch_op.f('ix_penerima_no_kk'), ['no_kk'], unique=False)

    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passing_grade', sa.Integer(), nullable=False),
    sa.Column('kuota', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('kriteria_penerima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penerima_id', sa.Integer(), nullable=False),
    sa.Column('nama_kriteria', sa.String(length=100), nullable=False),
    sa.Column('nilai_kriteria', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kriteria_penerima')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('setting')
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penerima_no_kk'))
        batch_op.drop_index(batch_op.f('ix_penerima_nik'))

    op.drop_table('penerima')
    # ### end Alembic commands ###
