"""Replace alamat_lengkap with location dropdowns

Revision ID: e48147382423
Revises: a1d2a14f178e
Create Date: 2025-07-15 12:25:53.108135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48147382423'
down_revision = 'a1d2a14f178e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pekerjaan', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.drop_column('pekerjaan')

    # ### end Alembic commands ###
