"""Initial migration after reset

Revision ID: eceb21079c4f
Revises: 
Create Date: 2025-07-17 02:55:02.849320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eceb21079c4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skor_saw_ternormalisasi', sa.Float(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_penerima_status_kelayakan_knn'))
        batch_op.drop_column('skor_knn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skor_knn', mysql.FLOAT(), nullable=True))
        batch_op.create_index(batch_op.f('ix_penerima_status_kelayakan_knn'), ['status_kelayakan_knn'], unique=False)
        batch_op.drop_column('skor_saw_ternormalisasi')

    # ### end Alembic commands ###
