"""Flatten Penerima model and remove KriteriaPenerima

Revision ID: f144e5dab94c
Revises: e48147382423
Create Date: 2025-07-15 18:22:28.581149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f144e5dab94c'
down_revision = 'e48147382423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('kriteria_penerima')

    # Manual data migration for 'dtks' column
    op.execute("UPDATE penerima SET dtks = 1 WHERE dtks = 'Ya'")
    op.execute("UPDATE penerima SET dtks = 0 WHERE dtks = 'Tidak' OR dtks IS NULL")

    with op.batch_alter_table('penerima', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('keluarga_miskin_ekstrem', sa.Boolean(), nullable=False, server_default='0'))
        # batch_op.add_column(sa.Column('kehilangan_mata_pencaharian', sa.Boolean(), nullable=False, server_default='0'))
        # batch_op.add_column(sa.Column('tidak_bekerja', sa.Boolean(), nullable=False, server_default='0'))
        # batch_op.add_column(sa.Column('difabel', sa.Boolean(), nullable=False, server_default='0'))
        # batch_op.add_column(sa.Column('penyakit_kronis', sa.Boolean(), nullable=False, server_default='0'))
        # batch_op.add_column(sa.Column('rumah_tangga_tunggal_lansia', sa.Boolean(), nullable=False, server_default='0'))
        # batch_op.add_column(sa.Column('pkh', sa.Boolean(), nullable=False, server_default='0'))
        # batch_op.add_column(sa.Column('kartu_pra_kerja', sa.Boolean(), nullable=False, server_default='0'))
        # batch_op.add_column(sa.Column('bst', sa.Boolean(), nullable=False, server_default='0'))
        # batch_op.add_column(sa.Column('bansos_lainnya', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('dtks',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Boolean(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_penerima_dtks'), ['dtks'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penerima', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penerima_dtks'))
        batch_op.alter_column('dtks',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('bansos_lainnya')
        batch_op.drop_column('bst')
        batch_op.drop_column('kartu_pra_kerja')
        batch_op.drop_column('pkh')
        batch_op.drop_column('rumah_tangga_tunggal_lansia')
        batch_op.drop_column('penyakit_kronis')
        batch_op.drop_column('difabel')
        batch_op.drop_column('tidak_bekerja')
        batch_op.drop_column('kehilangan_mata_pencaharian')
        batch_op.drop_column('keluarga_miskin_ekstrem')

    op.create_table('kriteria_penerima',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('penerima_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nama_kriteria', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nilai_kriteria', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima.id'], name=op.f('kriteria_penerima_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
